name: PR Approval

on:
    pull_request_review:
        types: [submitted]
    workflow_dispatch:
        inputs:
            pr_title:
                description: "Pull Request Title (for testing)"
                required: true
                default: "Update feature #12345"

jobs:
    update-backlog-status:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR approval
              id: check_pr_approval
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    echo "approved=true" >> $GITHUB_OUTPUT
                  elif [ "${{ github.event.review.state }}" = "approved" ]; then
                    echo "approved=true" >> $GITHUB_OUTPUT
                  else
                    echo "approved=false" >> $GITHUB_OUTPUT
                  fi
              shell: bash

            - name: Extract entryId from PR title
              id: extract_entry_id
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    PR_TITLE="${{ github.event.inputs.pr_title }}"
                  else
                    PR_TITLE="${{ github.event.pull_request.title }}"
                  fi
                  ENTRY_ID=$(echo "$PR_TITLE" | grep -oE '[0-9]+$' || echo "")
                  echo "entry_id=$ENTRY_ID" >> $GITHUB_OUTPUT
              shell: bash

            - name: Call External API
              if: steps.check_pr_approval.outputs.approved == 'true'
              run: |
                  curl -X PUT "https://apistaging.clevero.co/api/v3/internal/features/dynamic/233450/${{ steps.extract_entry_id.outputs.entry_id }}" \
                        -H "accept: application/json, text/plain, */*" \
                        -H "accept-language: en-US,en;q=0.9" \
                        -H "authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5EVkdOalk1UlRnelJrUkJRVEV5UkVVM1FqVkZNemxGUVRSRVEwRkdPREpGT1VRek5FRTBSQSJ9.eyJpc3MiOiJodHRwczovL2F1dGguY2xldmVyby5jby8iLCJzdWIiOiJhdXRoMHw2Mzg5MjkwNWE0MjE2ZDI0Zjc3MjZhOTEiLCJhdWQiOlsiaHR0cHM6Ly93d3cua2FseXN5cy5jb20vIiwiaHR0cHM6Ly9sZXp5ZW9oLmF1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3NDA0Nzc1OTcsImV4cCI6MTc0MDUyMDc5Nywic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImF6cCI6IjJEbFU1NndiSTRLdkpzTW9ZSGc1bXdQVTMzUHJnOXM0In0.s7bB69EKDnbEm0gQapeYSMUKwvekTXepBBwcKKdV2Lxm07IhJqc74CE3pzdWN3vgfiuwv05vCE27E3o3chIpuyXr1cDepWulhPLGvx8Ma6vm-v9u3LEwDuxN2shN8Hn_achLc2xT9bl5KHylw4MbqjxUYN1lH4nsAlUHafKBxEBVNMItbX04HSHElkwMJ4GiSTTxERjTyaD3ww_H84MhQM4wx5enQ0PtOoSGT24icqQW_N19IBxvDpyJGUACB5rrvX7j5-44DVydo538GpTzyW12W5ebwLJBlB7mBhBemS2HuvvG-CpzeZRu_quLCyKGnN3D2XqKG_-B2n6NFYBD8A" \
                        -H "content-type: application/json;charset=UTF-8" \
                        -H "origin: https://staging.clevero.co" \
                        -H "priority: u=1, i" \
                        -H "referer: https://staging.clevero.co/" \
                        -H "role: 126" \
                        -H "sec-ch-ua: \"Not(A:Brand\";v=\"99\", \"Microsoft Edge\";v=\"133\", \"Chromium\";v=\"133\"" \
                        -H "sec-ch-ua-mobile: ?0" \
                        -H "sec-ch-ua-platform: \"Windows\"" \
                        -H "sec-fetch-dest: empty" \
                        -H "sec-fetch-mode: cors" \
                        -H "sec-fetch-site: same-site" \
                        -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0" \
                        --data-raw '{"values":{"status":["2351441"]},"subrecords":{"toAdd":{},"toEdit":{},"toDelete":{},"subrecordInternalIds":[]}}'
              env:
                  API_SECRET: ${{ secrets.API_SECRET }}
